### ISSUE TITLE
Clarify naming requirements

### ISSUE THREAD

**Issue by JesseWeinstein** [jjjake/ia_plugin#1]
By looking at the plugin loading code ( https://github.com/jjjake/internetarchive/blob/master/internetarchive/cli/ia.py#L89-L93 ) I see that the module name must start with "ia_" and the rest of the name is how it will be referred to when using it. For consistency, probably the whole repo, and the stand-alone tool, should also have the same name (albeit with underscores switched for dashes). Please add this to the documentation.

**Comment by JesseWeinstein** [comment]
This may be addressed by PR #2

**Comment by jjjake** [comment]
I think PR #2 does a good enough job for right now.

I would like to create proper documentation for `ia` plugins, so I can provide better documentation when I do that.
